FROM amd64/debian
ENV CONTAINER_VERSION=0.1 \
    DISPLAY=:1 \
    DEBIAN_FRONTEND=noninteractive \
    PUID=0 \
    PGID=0
RUN echo 'deb http://deb.debian.org/debian stretch-backports main' >> /etc/apt/sources.list && \
    dpkg --add-architecture i386 && \
    apt-get update && \
    apt install -y wine32 libwine:i386 fonts-wine

FROM scratch
COPY --from=0 / /
